version: "3.4"

# docker-compose -f docker-compose-btc.yml up

# https://bitcoincore.org/en/doc/0.19.0/
# curl -v --data-binary '{"jsonrpc":"1.0","id":"1","method":"getnetworkinfo","params":[]}' http://bitcoin:verysecure@localhost:18332/
# docker run -it --network=host --rm ruimarinho/bitcoin-core bitcoin-cli -rpcconnect=localhost -rpcuser=bitcoin -rpcpassword=verysecure -testnet getmininginfo
# docker-compose exec --user bitcoin bitcoind bitcoin-cli -rpcuser=bitcoin -rpcpassword=verysecure -testnet getmininginfo
services:
  bitcoind:
    image: ruimarinho/bitcoin-core
    # https://github.com/bitcoin/bitcoin/blob/master/share/examples/bitcoin.conf
    command: -printtoconsole -server=1 -testnet=1 -prune=550 -rpcallowip=0.0.0.0/0 -rpcbind=0.0.0.0 -rpcuser=bitcoin -rpcpassword=verysecure
    volumes:
      - ./bitcoin-data:/home/bitcoin/.bitcoin
    ports:
      - 18332:18332 # json-rpc (testnet)
